name: "conventional_commit"
description: "Parse a conventional Git commit message."
version: "0.1.0+1"
homepage: "https://github.com/invertase/melos/tree/master/packages/conventional_commit"
dev_dependencies:
  test: any
environment:
  sdk: ">=2.2.2 <3.0.0"
